version: "3.5"
services:
  nextcloud:
    build:
      context: nextcloud
      args:
        UPSTREAM_VERSION: 34.0.3
    container_name: nextcloud.nextcloud.public.dappnode.eth
    volumes:
      - nextcloud-data:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_dappnode_pass
      MYSQL_HOST: DAppNodePackage-db.nextcloud.public.dappnode.eth
      REDIS_HOST: DAppNodePackage-redis.nextcloud.public.dappnode.eth
      REDIS_HOST_PORT: "6379"
      APACHE_LISTEN_PORT: "8034"
      APACHE_PORT: "8034"
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.dappnode
      OVERWRITEPROTOCOL: http
  db:
    build:
      context: db
    container_name: db.nextcloud.public.dappnode.eth
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud_root_dappnode_pass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud_dappnode_pass
  redis:
    build:
      context: redis
    container_name: redis.nextcloud.public.dappnode.eth
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
volumes:
  nextcloud-data: {}
  db-data: {}
  redis-data: {}
